platform :ios, '10.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target 'TRXWallet' do
    use_frameworks!
    
    pod 'BigInt', '~> 3.0'
    pod 'R.swift'
    pod 'JSONRPCKit', :git=> 'https://github.com/bricklife/JSONRPCKit.git'
    pod 'PromiseKit', '~> 6.0'
    pod 'APIKit'
    pod 'Eureka', '~> 4.1.1'
    pod 'MBProgressHUD'
    pod 'StatefulViewController'
    pod 'QRCodeReaderViewController', :git=>'https://github.com/yannickl/QRCodeReaderViewController.git', :branch=>'master'
    pod 'KeychainSwift'
    pod 'SwiftLint'
    pod 'SeedStackViewController'
    pod 'RealmSwift', '~> 3.7.4'
    pod 'Lokalise'
    pod 'Moya'
    pod 'Moya/RxSwift'
    pod 'ObjectMapper'
    pod 'CryptoSwift', '0.8.0'
    pod 'Fabric'
    pod 'Crashlytics', '~> 3.10'
    pod 'Firebase/Core'
    pod 'Kingfisher', '~> 4.0'
    pod 'TrustCore', '~> 0.0.6'
    pod 'TrustKeystore', '~> 0.4.0'
    pod 'Branch'
    # pod 'web3swift', :git=>'https://github.com/BANKEX/web3swift', :branch=>'master'
    pod 'SAMKeychain'
    pod 'TrustWeb3Provider', :git=>'https://github.com/TrustWallet/trust-web3-provider', :branch=>'master'
    pod 'JdenticonSwift'
    pod 'URLNavigator'
    pod 'Ruler'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxGesture'
    pod 'SnapKit'
    pod 'pop'
    pod 'Protobuf'
    pod 'gRPC'
    pod 'gRPC-Core'
    pod 'gRPC-ProtoRPC'
    pod 'gRPC-RxLibrary'
    pod '!ProtoCompiler'
    pod '!ProtoCompiler-gRPCPlugin'
    pod 'Reveal-SDK', :configurations => ['Debug']
    #cell 高度
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'IQKeyboardManagerSwift'
    pod 'SwipeCellKit'
    
    pod 'HMSegmentedControl'
    pod 'DZNEmptyDataSet'
    pod 'MJRefresh'
    pod 'Bugly'
    
    pod 'Firebase/Core'
    pod 'Firebase/RemoteConfig'
end

# target 'OpenInTrust' do
#   use_frameworks!
#   pod 'Result'
# end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['JSONRPCKit'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
        if ['TrustKeystore'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
            end
        end
    end
end
