// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class TronAccount;
@class Address;
@class AssetIssueContract;
@class Block;
@class BlockExtention;
@class BlockHeader;
@class Exchange;
@class Node;
@class Proposal;
@class Return;
@class TimeMessage;
@class TronTransaction;
@class TransactionExtention;
@class Witness;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Return_response_code

typedef GPB_ENUM(Return_response_code) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Return_response_code_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Return_response_code_Success = 0,

  /** error in signature */
  Return_response_code_Sigerror = 1,
  Return_response_code_ContractValidateError = 2,
  Return_response_code_ContractExeError = 3,
  Return_response_code_BandwithError = 4,
  Return_response_code_DupTransactionError = 5,
  Return_response_code_TaposError = 6,
  Return_response_code_TooBigTransactionError = 7,
  Return_response_code_TransactionExpirationError = 8,
  Return_response_code_ServerBusy = 9,
  Return_response_code_OtherError = 20,
};

GPBEnumDescriptor *Return_response_code_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Return_response_code_IsValidValue(int32_t value);

#pragma mark - ApiRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ApiRoot : GPBRootObject
@end

#pragma mark - Return

typedef GPB_ENUM(Return_FieldNumber) {
  Return_FieldNumber_Result = 1,
  Return_FieldNumber_Code = 2,
  Return_FieldNumber_Message = 3,
};

@interface Return : GPBMessage

@property(nonatomic, readwrite) BOOL result;

@property(nonatomic, readwrite) Return_response_code code;

@property(nonatomic, readwrite, copy, null_resettable) NSData *message;

@end

/**
 * Fetches the raw value of a @c Return's @c code property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Return_Code_RawValue(Return *message);
/**
 * Sets the raw value of an @c Return's @c code property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetReturn_Code_RawValue(Return *message, int32_t value);

#pragma mark - BlockReference

typedef GPB_ENUM(BlockReference_FieldNumber) {
  BlockReference_FieldNumber_BlockNum = 1,
  BlockReference_FieldNumber_BlockHash = 2,
};

@interface BlockReference : GPBMessage

@property(nonatomic, readwrite) int64_t blockNum;

@property(nonatomic, readwrite, copy, null_resettable) NSData *blockHash;

@end

#pragma mark - WitnessList

typedef GPB_ENUM(WitnessList_FieldNumber) {
  WitnessList_FieldNumber_WitnessesArray = 1,
};

@interface WitnessList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Witness*> *witnessesArray;
/** The number of items in @c witnessesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger witnessesArray_Count;

@end

#pragma mark - ProposalList

typedef GPB_ENUM(ProposalList_FieldNumber) {
  ProposalList_FieldNumber_ProposalsArray = 1,
};

@interface ProposalList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Proposal*> *proposalsArray;
/** The number of items in @c proposalsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger proposalsArray_Count;

@end

#pragma mark - ExchangeList

typedef GPB_ENUM(ExchangeList_FieldNumber) {
  ExchangeList_FieldNumber_ExchangesArray = 1,
};

@interface ExchangeList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Exchange*> *exchangesArray;
/** The number of items in @c exchangesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger exchangesArray_Count;

@end

#pragma mark - AssetIssueList

typedef GPB_ENUM(AssetIssueList_FieldNumber) {
  AssetIssueList_FieldNumber_AssetIssueArray = 1,
};

@interface AssetIssueList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AssetIssueContract*> *assetIssueArray;
/** The number of items in @c assetIssueArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger assetIssueArray_Count;

@end

#pragma mark - BlockList

typedef GPB_ENUM(BlockList_FieldNumber) {
  BlockList_FieldNumber_BlockArray = 1,
};

@interface BlockList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Block*> *blockArray;
/** The number of items in @c blockArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger blockArray_Count;

@end

#pragma mark - TransactionList

typedef GPB_ENUM(TransactionList_FieldNumber) {
  TransactionList_FieldNumber_TransactionArray = 1,
};

@interface TransactionList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TronTransaction*> *transactionArray;
/** The number of items in @c transactionArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transactionArray_Count;

@end

#pragma mark - NodeList

typedef GPB_ENUM(NodeList_FieldNumber) {
  NodeList_FieldNumber_NodesArray = 1,
};

/**
 * Gossip node list
 **/
@interface NodeList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Node*> *nodesArray;
/** The number of items in @c nodesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger nodesArray_Count;

@end

#pragma mark - Node

typedef GPB_ENUM(Node_FieldNumber) {
  Node_FieldNumber_Address = 1,
};

/**
 * Gossip node
 **/
@interface Node : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Address *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - Address

typedef GPB_ENUM(Address_FieldNumber) {
  Address_FieldNumber_Host = 1,
  Address_FieldNumber_Port = 2,
};

/**
 * Gossip node address
 **/
@interface Address : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *host;

@property(nonatomic, readwrite) int32_t port;

@end

#pragma mark - EmptyMessage

@interface EmptyMessage : GPBMessage

@end

#pragma mark - NumberMessage

typedef GPB_ENUM(NumberMessage_FieldNumber) {
  NumberMessage_FieldNumber_Num = 1,
};

@interface NumberMessage : GPBMessage

@property(nonatomic, readwrite) int64_t num;

@end

#pragma mark - BytesMessage

typedef GPB_ENUM(BytesMessage_FieldNumber) {
  BytesMessage_FieldNumber_Value = 1,
};

@interface BytesMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *value;

@end

#pragma mark - TimeMessage

typedef GPB_ENUM(TimeMessage_FieldNumber) {
  TimeMessage_FieldNumber_BeginInMilliseconds = 1,
  TimeMessage_FieldNumber_EndInMilliseconds = 2,
};

@interface TimeMessage : GPBMessage

@property(nonatomic, readwrite) int64_t beginInMilliseconds;

@property(nonatomic, readwrite) int64_t endInMilliseconds;

@end

#pragma mark - BlockLimit

typedef GPB_ENUM(BlockLimit_FieldNumber) {
  BlockLimit_FieldNumber_StartNum = 1,
  BlockLimit_FieldNumber_EndNum = 2,
};

@interface BlockLimit : GPBMessage

@property(nonatomic, readwrite) int64_t startNum;

@property(nonatomic, readwrite) int64_t endNum;

@end

#pragma mark - TransactionLimit

typedef GPB_ENUM(TransactionLimit_FieldNumber) {
  TransactionLimit_FieldNumber_TransactionId = 1,
  TransactionLimit_FieldNumber_LimitNum = 2,
};

@interface TransactionLimit : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *transactionId;

@property(nonatomic, readwrite) int64_t limitNum;

@end

#pragma mark - AccountPaginated

typedef GPB_ENUM(AccountPaginated_FieldNumber) {
  AccountPaginated_FieldNumber_Account = 1,
  AccountPaginated_FieldNumber_Offset = 2,
  AccountPaginated_FieldNumber_Limit = 3,
};

@interface AccountPaginated : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TronAccount *account;
/** Test to see if @c account has been set. */
@property(nonatomic, readwrite) BOOL hasAccount;

@property(nonatomic, readwrite) int64_t offset;

@property(nonatomic, readwrite) int64_t limit;

@end

#pragma mark - TimePaginatedMessage

typedef GPB_ENUM(TimePaginatedMessage_FieldNumber) {
  TimePaginatedMessage_FieldNumber_TimeMessage = 1,
  TimePaginatedMessage_FieldNumber_Offset = 2,
  TimePaginatedMessage_FieldNumber_Limit = 3,
};

@interface TimePaginatedMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TimeMessage *timeMessage;
/** Test to see if @c timeMessage has been set. */
@property(nonatomic, readwrite) BOOL hasTimeMessage;

@property(nonatomic, readwrite) int64_t offset;

@property(nonatomic, readwrite) int64_t limit;

@end

#pragma mark - AccountNetMessage

typedef GPB_ENUM(AccountNetMessage_FieldNumber) {
  AccountNetMessage_FieldNumber_FreeNetUsed = 1,
  AccountNetMessage_FieldNumber_FreeNetLimit = 2,
  AccountNetMessage_FieldNumber_NetUsed = 3,
  AccountNetMessage_FieldNumber_NetLimit = 4,
  AccountNetMessage_FieldNumber_AssetNetUsed = 5,
  AccountNetMessage_FieldNumber_AssetNetLimit = 6,
  AccountNetMessage_FieldNumber_TotalNetLimit = 7,
  AccountNetMessage_FieldNumber_TotalNetWeight = 8,
};

/**
 * deprecated
 **/
@interface AccountNetMessage : GPBMessage

@property(nonatomic, readwrite) int64_t freeNetUsed;

@property(nonatomic, readwrite) int64_t freeNetLimit;

@property(nonatomic, readwrite) int64_t netUsed;

@property(nonatomic, readwrite) int64_t netLimit;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *assetNetUsed;
/** The number of items in @c assetNetUsed without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger assetNetUsed_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *assetNetLimit;
/** The number of items in @c assetNetLimit without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger assetNetLimit_Count;

@property(nonatomic, readwrite) int64_t totalNetLimit;

@property(nonatomic, readwrite) int64_t totalNetWeight;

@end

#pragma mark - AccountResourceMessage

typedef GPB_ENUM(AccountResourceMessage_FieldNumber) {
  AccountResourceMessage_FieldNumber_FreeNetUsed = 1,
  AccountResourceMessage_FieldNumber_FreeNetLimit = 2,
  AccountResourceMessage_FieldNumber_NetUsed = 3,
  AccountResourceMessage_FieldNumber_NetLimit = 4,
  AccountResourceMessage_FieldNumber_AssetNetUsed = 5,
  AccountResourceMessage_FieldNumber_AssetNetLimit = 6,
  AccountResourceMessage_FieldNumber_TotalNetLimit = 7,
  AccountResourceMessage_FieldNumber_TotalNetWeight = 8,
  AccountResourceMessage_FieldNumber_EnergyUsed = 13,
  AccountResourceMessage_FieldNumber_EnergyLimit = 14,
  AccountResourceMessage_FieldNumber_TotalEnergyLimit = 15,
  AccountResourceMessage_FieldNumber_TotalEnergyWeight = 16,
  AccountResourceMessage_FieldNumber_StorageUsed = 21,
  AccountResourceMessage_FieldNumber_StorageLimit = 22,
};

@interface AccountResourceMessage : GPBMessage

@property(nonatomic, readwrite) int64_t freeNetUsed;

@property(nonatomic, readwrite) int64_t freeNetLimit;

@property(nonatomic, readwrite) int64_t netUsed;

@property(nonatomic, readwrite) int64_t netLimit;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *assetNetUsed;
/** The number of items in @c assetNetUsed without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger assetNetUsed_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *assetNetLimit;
/** The number of items in @c assetNetLimit without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger assetNetLimit_Count;

@property(nonatomic, readwrite) int64_t totalNetLimit;

@property(nonatomic, readwrite) int64_t totalNetWeight;

@property(nonatomic, readwrite) int64_t energyUsed;

@property(nonatomic, readwrite) int64_t energyLimit;

@property(nonatomic, readwrite) int64_t totalEnergyLimit;

@property(nonatomic, readwrite) int64_t totalEnergyWeight;

@property(nonatomic, readwrite) int64_t storageUsed;

@property(nonatomic, readwrite) int64_t storageLimit;

@end

#pragma mark - PaginatedMessage

typedef GPB_ENUM(PaginatedMessage_FieldNumber) {
  PaginatedMessage_FieldNumber_Offset = 1,
  PaginatedMessage_FieldNumber_Limit = 2,
};

@interface PaginatedMessage : GPBMessage

@property(nonatomic, readwrite) int64_t offset;

@property(nonatomic, readwrite) int64_t limit;

@end

#pragma mark - EasyTransferMessage

typedef GPB_ENUM(EasyTransferMessage_FieldNumber) {
  EasyTransferMessage_FieldNumber_PassPhrase = 1,
  EasyTransferMessage_FieldNumber_ToAddress = 2,
  EasyTransferMessage_FieldNumber_Amount = 3,
};

@interface EasyTransferMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *passPhrase;

@property(nonatomic, readwrite, copy, null_resettable) NSData *toAddress;

@property(nonatomic, readwrite) int64_t amount;

@end

#pragma mark - EasyTransferByPrivateMessage

typedef GPB_ENUM(EasyTransferByPrivateMessage_FieldNumber) {
  EasyTransferByPrivateMessage_FieldNumber_PrivateKey = 1,
  EasyTransferByPrivateMessage_FieldNumber_ToAddress = 2,
  EasyTransferByPrivateMessage_FieldNumber_Amount = 3,
};

@interface EasyTransferByPrivateMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *privateKey;

@property(nonatomic, readwrite, copy, null_resettable) NSData *toAddress;

@property(nonatomic, readwrite) int64_t amount;

@end

#pragma mark - EasyTransferResponse

typedef GPB_ENUM(EasyTransferResponse_FieldNumber) {
  EasyTransferResponse_FieldNumber_Transaction = 1,
  EasyTransferResponse_FieldNumber_Result = 2,
  EasyTransferResponse_FieldNumber_Txid = 3,
};

@interface EasyTransferResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TronTransaction *transaction;
/** Test to see if @c transaction has been set. */
@property(nonatomic, readwrite) BOOL hasTransaction;

@property(nonatomic, readwrite, strong, null_resettable) Return *result;
/** Test to see if @c result has been set. */
@property(nonatomic, readwrite) BOOL hasResult;

/** transaction id =  sha256(transaction.rowdata) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *txid;

@end

#pragma mark - AddressPrKeyPairMessage

typedef GPB_ENUM(AddressPrKeyPairMessage_FieldNumber) {
  AddressPrKeyPairMessage_FieldNumber_Address = 1,
  AddressPrKeyPairMessage_FieldNumber_PrivateKey = 2,
};

@interface AddressPrKeyPairMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite, copy, null_resettable) NSString *privateKey;

@end

#pragma mark - TransactionExtention

typedef GPB_ENUM(TransactionExtention_FieldNumber) {
  TransactionExtention_FieldNumber_Transaction = 1,
  TransactionExtention_FieldNumber_Txid = 2,
  TransactionExtention_FieldNumber_ConstantResultArray = 3,
  TransactionExtention_FieldNumber_Result = 4,
};

@interface TransactionExtention : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TronTransaction *transaction;
/** Test to see if @c transaction has been set. */
@property(nonatomic, readwrite) BOOL hasTransaction;

/** transaction id =  sha256(transaction.rowdata) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *txid;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSData*> *constantResultArray;
/** The number of items in @c constantResultArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger constantResultArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) Return *result;
/** Test to see if @c result has been set. */
@property(nonatomic, readwrite) BOOL hasResult;

@end

#pragma mark - BlockExtention

typedef GPB_ENUM(BlockExtention_FieldNumber) {
  BlockExtention_FieldNumber_TransactionsArray = 1,
  BlockExtention_FieldNumber_BlockHeader = 2,
  BlockExtention_FieldNumber_Blockid = 3,
};

@interface BlockExtention : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TransactionExtention*> *transactionsArray;
/** The number of items in @c transactionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transactionsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) BlockHeader *blockHeader;
/** Test to see if @c blockHeader has been set. */
@property(nonatomic, readwrite) BOOL hasBlockHeader;

@property(nonatomic, readwrite, copy, null_resettable) NSData *blockid;

@end

#pragma mark - BlockListExtention

typedef GPB_ENUM(BlockListExtention_FieldNumber) {
  BlockListExtention_FieldNumber_BlockArray = 1,
};

@interface BlockListExtention : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BlockExtention*> *blockArray;
/** The number of items in @c blockArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger blockArray_Count;

@end

#pragma mark - TransactionListExtention

typedef GPB_ENUM(TransactionListExtention_FieldNumber) {
  TransactionListExtention_FieldNumber_TransactionArray = 1,
};

@interface TransactionListExtention : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TransactionExtention*> *transactionArray;
/** The number of items in @c transactionArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transactionArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
